times:
  division_rate: 1
  max_time: 10
  samples: 100
population:
  initial_cells: 100
fitness:
  fitness_array: 1  # For initial clones. Integers be converted to a list
  mutation_rates: 0
  initial_mutant_gene_array: -1  # For the genes of initial clones. Integers be converted to a list. -1 means not associated with a gene.
labels:
  label_array: 0   # For initial clones. Integers be converted to a list
treatment:
  treatment_effect: 1
differentiated_cells:
  stratification_sim_percentile: 1
plotting:
  figsize: [10, 10]

